{
  organization(login: "rsource-open-source") {
    repositories(privacy: PUBLIC, first: 50) {
      edges {
        node {
          name
          description
          stargazerCount
          openGraphImageUrl
          primaryLanguage {
            name
          }
          homepageUrl
          usesCustomOpenGraphImage
          url
        }
      }
    }
  }
}
