import type { NextPage } from "next";
import Head from "next/head";
import { routes } from "../public/routes";

let mappedRoutes = "";
for (const [k, v] of Object.entries(routes)) mappedRoutes += `\n${k} => ${v}`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>rsource community</title>
        <meta content="rsource community" property="og:title"></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <pre>
          <h1>rsource community</h1>
          <p>available redirects:</p>
          <p>{mappedRoutes}</p>
        </pre>
      </main>
    </div>
  );
};

export default Home;
