import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>rsource community</title>
        <meta content="rsource community" property="og:title"></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src="/../public/assets/rsource_bg.png"
        layout="fill"
        className="bgWrap"
        objectPosition="center"
      ></Image>
      <main>
        <h1>coming soon</h1>
        <p>test</p>
      </main>
    </div>
  );
};

export default Home;
