import type { NextPage } from "next";
import Head from "next/head";
import figlet from "figlet";

const Home: NextPage = () => {
  console.log(window);
  let title = figlet.textSync("rsource.community", "Slant");
  return (
    <div>
      <Head>
        <title>rsource community</title>
        <meta content="rsource community" property="og:title"></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>{title}</p>
      </main>
    </div>
  );
};

export default Home;
